APP_WIDE_SCR_MULT: 1.2  # the app window is considered wide when wide*app_wide_scr_mult > height

ERROR_MSG_BG_COLOR: [1, 0.85, 0.84]
ERR_TEXT_LENGTH_CORR_DIV: 1.2
ERR_BASE_FONT_MLT_NARROW: 0.067
ERR_ICON_BASE_FONT_MLT_WIDE: 0.9
ERR_ICON_BASE_FONT_MLT_NARROW: 1

# ------for sizable buttons
BTN_ROOT_WIDTH_MLT: 0.8
BTN_BASE_FONT_MLT: 0.7

# ------for text in controlbox
CTRL_LBL_BASE_FONT_MLT_WIDE: 0.8
CTRL_LBL_BASE_FONT_MLT_NARROW: 0.08

# ------for drop menu
DROP_MENU_WIDTH_DIV: 1.5
DROP_MENU_MAX_WIDTH: 700
DROP_MENU_TEXT_LENGTH_CORR_DIV: 1.4
DROP_MENU_BASE_FONT_MLT_WIDE: 0.038
DROP_MENU_BASE_FONT_MLT_NARROW: 0.08

#------for integral parameters widget
P_WIDG_BASE_FONT_MLT: 0.25
P_SECTION_HEIGHT: 85

# ------default values for font size config
TEXT_LENGTH_CORR_DIV: 1.5
BASE_FONT_MLT_WIDE: 0.5
BASE_FONT_MLT_NARROW: 0.07